logsBucket: gs://development-437521.appspot.com

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west4-docker.pkg.dev/development-437521/test-deployment/my-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west4-docker.pkg.dev/development-437521/test-deployment/my-app:latest']


images:
  - 'us-west4-docker.pkg.dev/development-437521/test-deployment/my-app:latest'
